### ISSUE TITLE
项目编译

### ISSUE THREAD

**Issue by xiaoguoer** [ZTMIDGO/Android-Stable-diffusion-ONNX#8]
你好，我尝试新建一个项目复现这个工程，就直接把代码copy到新项目里。
发现在运行的时候，点击 生成 按钮，就报错：
`java.lang.UnsatisfiedLinkError: No implementation found for long ai.onnxruntime.OrtSession$SessionOptions.createOptions(long) (tried Java_ai_onnxruntime_OrtSession_00024SessionOptions_createOptions and Java_ai_onnxruntime_OrtSession_00024SessionOptions_createOptions__J)
                                                                                                    	at ai.onnxruntime.OrtSession$SessionOptions.createOptions(Native Method)
                                                                                                    	at ai.onnxruntime.OrtSession$SessionOptions.<init>(OrtSession.java:530)
                                                                                                    	at com.xiaoguo.demo.diffusion.tokenizer.EngTokenizer.init(EngTokenizer.java:59)`

请问在编译过程中，有什么需要注意的么？

**Comment by ZTMIDGO** [comment]
似乎是导入onnxruntime模块的错误，是否是使用Android studio编译代码？

**Comment by xiaoguoer** [comment]
@ZTMIDGO 是的。不太熟悉Android studio，看到你的项目里在 gradle的dependencies里面有一行 onnxruntime 的implementation，我也加了一行。不知道这么做对不对

**Comment by xiaoguoer** [comment]
参考 [onnxruntime/issues/16434](https://github.com/microsoft/onnxruntime/issues/16434) 解决了。
